services:
  mml-ogr-client:
    image: ${MML_OGR_IMAGE}
    build: ../mml-ogc-processes
    env_file:
      - ../mml-ogc-processes/.env
    volumes:
      - /opt/mtkdata:/mtkdata
      - /opt/krkdata:/krkdata

  rs-ogr2osm:
    image: ${OGR2OSM_IMAGE}
    build: ../../rs-ogr2osm
    profiles: [release]

  osmium:
    image: ${OSMIUM_IMAGE}
    build: ./ubuntugis-base
    profiles: [release]

  mapsforge-rs:
    image: ${MAPSFORGE_RS_IMAGE}
    build: ../../rs-mapsforge-writer
    volumes:
      - ${MTK2GARMIN_BUILD_ROOT:-/opt/mtk2garmin-build}/convertedpbf:/convertedpbf
      - mapstyle:/mapstyles
      - ${MTK2GARMIN_BUILD_ROOT:-/opt/mtk2garmin-build}/output:/output

  osxconverter:
    image: ${OSXCONVERTER_IMAGE}
    build: ../garminOSXConverter
    volumes:
      - ${MTK2GARMIN_BUILD_ROOT:-/opt/mtk2garmin-build}/output:/output

  additional-data:
    image: ${ADDITIONAL_DATA_IMAGE}
    build: ../get-additional-data
    volumes:
      - additional-data:/additional-data

  mkgmap:
    image: ${MKGMAP_IMAGE}
    build: ../mkgmap-converter
    volumes:
      - ${MTK2GARMIN_BUILD_ROOT:-/opt/mtk2garmin-build}/convertedpbf:/convertedpbf
      - ${MTK2GARMIN_BUILD_ROOT:-/opt/mtk2garmin-build}/splitted:/splitted
      - ${MTK2GARMIN_BUILD_ROOT:-/opt/mtk2garmin-build}/output:/output
      - mapstyle:/mapstyles

  mapstyles:
    image: ${MAPSTYLES_IMAGE}
    build: ../mapstyles
    volumes:
      - mapstyle:/mapstyles

  nsis:
    image: ${NSIS_IMAGE}
    volumes:
      - ${MTK2GARMIN_BUILD_ROOT:-/opt/mtk2garmin-build}/output:/output

  site:
    image: ${SITE_IMAGE}
    build: ../site
    env_file:
      - aws-access.env
    volumes:
      - ${MTK2GARMIN_BUILD_ROOT:-/opt/mtk2garmin-build}/output:/output
      - ${MTK2GARMIN_PUBLISH_ROOT:-/opt/mtk2garmin-publish}:/publish
      - mapstyle:/mapstyles

volumes:
  additional-data:
  mapstyle:
